package weddellseal.markrecap.frameworks.room.observations

data class Seal(
    val age: String = "",
    val ageYears: String = "",
    val colony: String = "",
    val comment: String = "",
    val condition: String = "",
    var flaggedForReview: Boolean = false,
    val hasWedCheckSpeno: Boolean = false,
    var isStarted: Boolean = false,
    var isNoTag: Boolean = false,
    val isValid: Boolean = false,
    val isValidated: Boolean = false,
    var isWedCheck: Boolean = false,
    val lastObservedDead: Boolean = false,
    val lastPhysio: String = "",
    val lastSeenSeason: Int = 0,
    val lastSeasonWithinTenYears: Boolean = false,
    val massPups: String = "",
    val name: String = "",
    val notebookDataString: String = "",
    val numRelatives: String = "",
    val numTags: String = "",
    val numTagsMatch: Boolean = false,
    val oldTagId: String = "",
    val oldTagMarks: Boolean = false,
    val photoYears: String = "",
    val previousPups: String = "",
    val pupPeed: Boolean = false,
    val reasonForRetag: String = "",
    val reasonNotValid: String = "",
    val sex: String = "",
    val sexMatch: Boolean = false,
    val speNo: Int = 0,
    val swimPups: String = "",
    val tagEventType: String = "",
    val tagAlpha: String = "",
    val tagNumber: String = "",
    val tissueTaken: Boolean = false,
    val tissue: String = "",
    val weight: Int = 0,
    val weightTaken: Boolean = false,
    val observationID : Int = 0,
    val isObservationLogEntry : Boolean = false,
)